# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Eleventy Build
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: v18.13.0

      - uses: giantswarm/install-binary-action@v2.0.0
        with:
          binary: "pagefind_extended"
          version: "1.0.4"
          download_url: "https://github.com/CloudCannon/pagefind/releases/download/v${version}/${binary}-v${version}-x86_64-unknown-linux-musl.tar.gz"
          tarball_binary_path: "${binary}"
          smoke_test: "${binary} --version"

      - run: npm ci

      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: twitter.halkeye.net
